## MGMT 6560 Project

### Model 1: Naive Model

#### Part 1 Basics

In [1]:
#Basic Imports
import numpy as np
import pandas as pd

In [2]:
#Load the data
train=pd.read_csv('./input/train.csv')
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,325300
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal,139400
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
24,25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
25,26,20,RL,110.0,14230,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,256300
26,27,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,134800
27,28,20,RL,98.0,11478,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,306000
28,29,20,RL,47.0,16321,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2006,WD,Normal,207500
29,30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,RL,60.0,21930,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,192140
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1432,1433,30,RL,60.0,10800,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,64500
1433,1434,60,RL,93.0,10261,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,186500
1434,1435,20,RL,80.0,17400,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,160000
1435,1436,20,RL,80.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2008,COD,Abnorml,174000
1436,1437,20,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,120500
1437,1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1438,1439,20,RM,90.0,7407,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal,149700
1439,1440,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,197000
1440,1441,70,RL,79.0,11526,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,191000
1441,1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1443,1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1444,1445,20,RL,63.0,8500,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,179600
1445,1446,85,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,129000
1446,1447,20,RL,NaN,26142,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1448,1449,50,RL,70.0,11767,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,112000
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1450,1451,90,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
#This code will be used later in part 5
y=train['SalePrice']

In [4]:
#Load the data
test=pd.read_csv('./input/test.csv')
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
5,1466,60,RL,75.0,10000,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
6,1467,20,RL,NaN,7980,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,GdPrv,Shed,500,3,2010,WD,Normal
7,1468,60,RL,63.0,8402,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
8,1469,20,RL,85.0,10176,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,WD,Normal
9,1470,20,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal
10,1471,120,RH,26.0,5858,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
11,1472,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,COD,Normal
12,1473,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
13,1474,160,RL,24.0,2280,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
14,1475,120,RL,24.0,2280,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
15,1476,60,RL,102.0,12858,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,New,Partial
16,1477,20,RL,94.0,12883,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,New,Partial
17,1478,20,RL,90.0,11520,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
18,1479,20,RL,79.0,14122,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,WD,Normal
19,1480,20,RL,110.0,14300,Pave,NaN,Reg,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
20,1481,60,RL,105.0,13650,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
21,1482,120,RL,41.0,7132,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
22,1483,20,RL,100.0,18494,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,WD,Normal
23,1484,120,RL,43.0,3203,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,WD,Normal
24,1485,80,RL,67.0,13300,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
25,1486,60,RL,63.0,8577,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
26,1487,60,RL,60.0,17433,Pave,NaN,IR2,Lvl,AllPub,...,256,0,NaN,NaN,NaN,0,1,2010,WD,Normal
27,1488,20,RL,73.0,8987,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
28,1489,20,FV,92.0,9215,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,New,Partial
29,1490,20,FV,84.0,10440,Pave,NaN,Reg,Lvl,AllPub,...,216,0,NaN,NaN,NaN,0,5,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2890,30,RM,50.0,7030,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2006,WD,Normal
1430,2891,50,RM,75.0,9060,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1431,2892,30,C (all),69.0,12366,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1432,2893,190,C (all),50.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1433,2894,50,C (all),60.0,8520,Grvl,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1434,2895,120,RM,41.0,5748,Pave,NaN,IR1,HLS,AllPub,...,153,0,NaN,NaN,NaN,0,2,2006,New,Partial
1435,2896,120,RM,44.0,3842,Pave,NaN,IR1,HLS,AllPub,...,155,0,NaN,NaN,NaN,0,12,2006,WD,Normal
1436,2897,20,RL,69.0,23580,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal
1437,2898,90,RL,65.0,8385,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1438,2899,20,RL,70.0,9116,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1439,2900,80,RL,140.0,11080,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1440,2901,20,RL,NaN,50102,Pave,NaN,IR1,Low,AllPub,...,138,0,NaN,NaN,NaN,0,3,2006,WD,Alloca
1441,2902,20,RL,NaN,8098,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1442,2903,20,RL,95.0,13618,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,New,Partial
1443,2904,20,RL,88.0,11577,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,New,Partial
1444,2905,20,NaN,125.0,31250,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1445,2906,90,RM,78.0,7020,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal
1446,2907,160,RM,41.0,2665,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1447,2908,20,RL,58.0,10172,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1448,2909,90,RL,NaN,11836,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2006,WD,Normal
1449,2910,180,RM,21.0,1470,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1450,2911,160,RM,21.0,1484,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1451,2912,20,RL,80.0,13384,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1452,2913,160,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Abnorml
1453,2914,160,RM,21.0,1526,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,6,2006,WD,Normal
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [5]:
testid=test['Id']

In [6]:
#Drop the Id column and SalePrice column in the training set. 
#The Id column will not be used in the model. And SalePrice will be the y for the training.
train=train.drop(['SalePrice'],axis=1)
train=train.drop(['Id'],axis=1)
train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [7]:
#Drop the Id column in the test set
#The Id column will not be used in the model.
test=test.drop(['Id'],axis=1)
test.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [8]:
#Before handle NaN and dummy variables, concatenate the train and test set. 
#So that deal with NaN and dummy variables will be done together. 
alldata=pd.concat([train,test],axis=0)
alldata.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

#### Part 2 Fill NaN values

In [9]:
#This code shows all numerical columns in the training set.
alldata._get_numeric_data().columns

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold'],
      dtype='object')

In [10]:
#For convenience I use this code to check how many null values are in these numerical (literally) columns
alldata[alldata._get_numeric_data().columns].isnull().sum()

MSSubClass         0
LotFrontage      486
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea        23
BsmtFinSF1         1
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       2
BsmtHalfBath       2
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt      159
GarageCars         1
GarageArea         1
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
dtype: int64

In [11]:
#Fill NaN using the mean of that column (by default ignored NaN)
alldata['LotFrontage']=alldata['LotFrontage'].fillna(alldata['LotFrontage'].mean())
alldata['MasVnrArea']=alldata['MasVnrArea'].fillna(alldata['MasVnrArea'].mean())

In [12]:
#For these columns, NaN simply means '0' as this property does not have a basement at all
alldata['BsmtFinSF1']=alldata['BsmtFinSF1'].fillna(0)
alldata['BsmtFinSF2']=alldata['BsmtFinSF2'].fillna(0)
alldata['BsmtUnfSF']=alldata['BsmtUnfSF'].fillna(0)
alldata['TotalBsmtSF']=alldata['TotalBsmtSF'].fillna(0)

In [13]:
#For these columns, NaN means 0 since there is no bathroom at the basement (or no basement at all)
alldata['BsmtFullBath']=alldata['BsmtFullBath'].fillna(0)
alldata['GarageArea']=alldata['GarageArea'].fillna(0)

In [14]:
#Based on previous results, GarageYrBlt column has 159 NaN. 
#NaN simply indictes: there is no garage at this property.
#These NaN values will be filled using the 0 to reflect the fact that there is no garage
alldata['GarageYrBlt']=alldata['GarageYrBlt'].fillna(0)

In [15]:
#For these columns, NaN means 0 since there is no garage
alldata['GarageCars']=alldata['GarageCars'].fillna(0)
alldata['BsmtHalfBath']=alldata['BsmtHalfBath'].fillna(0)

In [16]:
#Now all NaN values in columns with numbers are filled. Now deal with NaN in other columns
#In these columns, NaN means 'None', as this property does not have something
#One function will get the job done. 
alldata=alldata.fillna('None')
alldata.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,None,Reg,Lvl,AllPub,FR2,...,0,0,None,None,None,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,None,IR1,Lvl,AllPub,Inside,...,0,0,None,None,None,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,None,IR1,Lvl,AllPub,Corner,...,0,0,None,None,None,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,None,IR1,Lvl,AllPub,FR2,...,0,0,None,None,None,0,12,2008,WD,Normal

In [17]:
#Check if there is still an NaN value
alldata.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
                ..
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
PoolQC           0
Fence            0
MiscFeature      0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 79, dtype: int64

#### Part 3 Create dummy variables

In [18]:
alldata=pd.get_dummies(alldata)
alldata.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0

#### Part 4 Train/Test Split (Back to the state before the concat)

In [19]:
train=alldata[:train.shape[0]]
train

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.000000,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.000000,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.000000,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.000000,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.000000,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0
5,50,85.000000,14115,5,5,1993,1995,0.0,732.0,0.0,...,0,0,0,1,0,0,0,0,1,0
6,20,75.000000,10084,8,5,2004,2005,186.0,1369.0,0.0,...,0,0,0,1,0,0,0,0,1,0
7,60,69.305795,10382,7,6,1973,1973,240.0,859.0,32.0,...,0,0,0,1,0,0,0,0,1,0
8,50,51.000000,6120,7,5,1931,1950,0.0,0.0,0.0,...,0,0,0,1,1,0,0,0,0,0
9,190,50.000000,7420,5,6,1939,1950,0.0,851.0,0.0,...,0,0,0,1,0,0,0,0,1,0
10,20,70.000000,11200,5,5,1965,1965,0.0,906.0,0.0,...,0,0,0,1,0,0,0,0,1,0
11,60,85.000000,11924,9,5,2005,2006,286.0,998.0,0.0,...,1,0,0,0,0,0,0,0,0,1
12,20,69.305795,12968,5,6,1962,1962,0.0,737.0,0.0,...,0,0,0,1,0,0,0,0,1,0
13,20,91.000000,10652,7,5,2006,2007,306.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
14,20,69.305795,10920,6,5,1960,1960,212.0,733.0,0.0,...,0,0,0,1,0,0,0,0,1,0
15,45,51.000000,6120,7,8,1929,2001,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
16,20,69.305795,11241,6,7,1970,1970,180.0,578.0,0.0,...,0,0,0,1,0,0,0,0,1,0
17,90,72.000000,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
18,20,66.000000,13695,5,5,2004,2004,0.0,646.0,0.0,...,0,0,0,1,0,0,0,0,1,0
19,20,70.000000,7560,5,6,1958,1965,0.0,504.0,0.0,...,0,0,0,0,1,0,0,0,0,0
20,60,101.000000,14215,8,5,2005,2006,380.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
21,45,57.000000,7449,7,7,1930,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
22,20,75.000000,9742,8,5,2002,2002,281.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
23,120,44.000000,4224,5,7,1976,1976,0.0,840.0,0.0,...,0,0,0,1,0,0,0,0,1,0
24,20,69.305795,8246,5,8,1968,2001,0.0,188.0,668.0,...,0,0,0,1,0,0,0,0,1,0
25,20,110.000000,14230,8,5,2007,2007,640.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
26,20,60.000000,7200,5,7,1951,2000,0.0,234.0,486.0,...,0,0,0,1,0,0,0,0,1,0
27,20,98.000000,11478,8,5,2007,2008,200.0,1218.0,0.0,...,0,0,0,1,0,0,0,0,1,0
28,20,47.000000,16321,5,6,1957,1997,0.0,1277.0,0.0,...,0,0,0,1,0,0,0,0,1,0
29,30,60.000000,6324,4,6,1927,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,60.000000,21930,5,5,2005,2005,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1431,120,69.305795,4928,6,6,1976,1976,0.0,958.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1432,30,60.000000,10800,4,6,1927,2007,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1433,60,93.000000,10261,6,5,2000,2000,318.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1434,20,80.000000,17400,5,5,1977,1977,0.0,936.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1435,20,80.000000,8400,6,9,1962,2005,237.0,0.0,0.0,...,0,0,0,0,1,0,0,0,0,0
1436,20,60.000000,9000,4,6,1971,1971,0.0,616.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1437,20,96.000000,12444,8,5,2008,2008,426.0,1336.0,0.0,...,1,0,0,0,0,0,0,0,0,1
1438,20,90.000000,7407,6,7,1957,1996,0.0,600.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1439,60,80.000000,11584,7,6,1979,1979,96.0,315.0,110.0,...,0,0,0,1,0,0,0,0,1,0
1440,70,79.000000,11526,6,7,1922,1994,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1441,120,69.305795,4426,6,5,2004,2004,147.0,697.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1442,60,85.000000,11003,10,5,2008,2008,160.0,765.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1443,30,69.305795,8854,6,6,1916,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1444,20,63.000000,8500,7,5,2004,2004,106.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1445,85,70.000000,8400,6,5,1966,1966,0.0,187.0,627.0,...,0,0,0,1,0,0,0,0,1,0
1446,20,69.305795,26142,5,7,1962,1962,189.0,593.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1447,60,80.000000,10000,8,5,1995,1996,438.0,1079.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1448,50,70.000000,11767,4,7,1910,2000,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1449,180,21.000000,1533,5,7,1970,1970,0.0,553.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1450,90,60.000000,9000,5,5,1974,1974,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1451,20,78.000000,9262,8,5,2008,2009,194.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
1452,180,35.000000,3675,5,5,2005,2005,80.0,547.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1453,20,90.000000,17217,5,5,2006,2006,0.0,0.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1454,20,62.000000,7500,7,5,2004,2005,0.0,410.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1455,60,62.000000,7917,6,5,1999,2000,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.000000,13175,6,6,1978,1988,119.0,790.0,163.0,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.000000,9042,7,9,1941,2006,0.0,275.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.000000,9717,5,6,1950,1996,0.0,49.0,1029.0,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.000000,9937,5,6,1965,1965,0.0,830.0,290.0,...,0,0,0,1,0,0,0,0,1,0

In [20]:
test=alldata[train.shape[0]:]
test

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,20,80.000000,11622,5,6,1961,1961,0.0,468.0,144.0,...,0,0,0,1,0,0,0,0,1,0
1,20,81.000000,14267,6,6,1958,1958,108.0,923.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,60,74.000000,13830,5,5,1997,1998,0.0,791.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,60,78.000000,9978,6,6,1998,1998,20.0,602.0,0.0,...,0,0,0,1,0,0,0,0,1,0
4,120,43.000000,5005,8,5,1992,1992,0.0,263.0,0.0,...,0,0,0,1,0,0,0,0,1,0
5,60,75.000000,10000,6,5,1993,1994,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
6,20,69.305795,7980,6,7,1992,2007,0.0,935.0,0.0,...,0,0,0,1,0,0,0,0,1,0
7,60,63.000000,8402,6,5,1998,1998,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
8,20,85.000000,10176,7,5,1990,1990,0.0,637.0,0.0,...,0,0,0,1,0,0,0,0,1,0
9,20,70.000000,8400,4,5,1970,1970,0.0,804.0,78.0,...,0,0,0,1,0,0,0,0,1,0
10,120,26.000000,5858,7,5,1999,1999,0.0,1051.0,0.0,...,0,0,0,1,0,0,0,0,1,0
11,160,21.000000,1680,6,5,1971,1971,504.0,156.0,0.0,...,0,0,0,0,0,0,0,0,1,0
12,160,21.000000,1680,5,5,1971,1971,492.0,300.0,0.0,...,0,0,0,1,0,0,0,0,1,0
13,160,24.000000,2280,6,6,1975,1975,0.0,514.0,0.0,...,0,0,0,1,0,0,0,0,1,0
14,120,24.000000,2280,7,6,1975,1975,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
15,60,102.000000,12858,9,5,2009,2010,162.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
16,20,94.000000,12883,8,5,2009,2010,256.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
17,20,90.000000,11520,9,5,2005,2005,615.0,110.0,0.0,...,0,0,0,1,0,0,0,0,1,0
18,20,79.000000,14122,8,5,2005,2006,240.0,28.0,0.0,...,0,0,0,1,0,0,0,0,1,0
19,20,110.000000,14300,9,5,2003,2004,1095.0,1373.0,0.0,...,0,0,0,1,0,0,0,0,1,0
20,60,105.000000,13650,8,5,2002,2002,232.0,578.0,0.0,...,0,0,0,1,0,0,0,0,1,0
21,120,41.000000,7132,8,5,2006,2006,178.0,24.0,0.0,...,0,0,0,1,0,0,0,0,1,0
22,20,100.000000,18494,6,5,2005,2005,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
23,120,43.000000,3203,7,5,2006,2006,14.0,16.0,0.0,...,0,0,0,1,0,0,0,0,1,0
24,80,67.000000,13300,7,5,2004,2004,0.0,326.0,0.0,...,0,0,0,1,0,0,0,0,1,0
25,60,63.000000,8577,7,5,2004,2004,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
26,60,60.000000,17433,8,5,1998,1998,114.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
27,20,73.000000,8987,8,5,2005,2006,226.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
28,20,92.000000,9215,7,5,2009,2010,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
29,20,84.000000,10440,6,5,2005,2005,0.0,1414.0,0.0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,30,50.000000,7030,4,6,1925,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1430,50,75.000000,9060,6,5,1957,1957,327.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1431,30,69.000000,12366,3,5,1945,1950,0.0,0.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1432,190,50.000000,9000,5,6,1951,1951,0.0,0.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1433,50,60.000000,8520,3,5,1916,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1434,120,41.000000,5748,8,5,2005,2006,473.0,1573.0,0.0,...,1,0,0,0,0,0,0,0,0,1
1435,120,44.000000,3842,8,5,2004,2005,186.0,1564.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1436,20,69.000000,23580,6,6,1979,1979,0.0,776.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1437,90,65.000000,8385,6,5,1978,1978,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1438,20,70.000000,9116,8,5,2001,2001,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1439,80,140.000000,11080,6,6,1975,1975,257.0,576.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1440,20,69.305795,50102,6,5,1958,1958,0.0,909.0,0.0,...,0,0,0,1,0,0,1,0,0,0
1441,20,69.305795,8098,6,5,2000,2000,0.0,1136.0,116.0,...,0,0,0,1,0,0,0,0,1,0
1442,20,95.000000,13618,8,5,2005,2006,198.0,1350.0,0.0,...,1,0,0,0,0,0,0,0,0,1
1443,20,88.000000,11577,9,5,2005,2006,382.0,1455.0,0.0,...,1,0,0,0,0,0,0,0,0,1
1444,20,125.000000,31250,1,3,1951,1951,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1445,90,78.000000,7020,7,5,1997,1997,200.0,1243.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1446,160,41.000000,2665,5,6,1977,1977,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1447,20,58.000000,10172,5,7,1968,2003,0.0,441.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1448,90,69.305795,11836,5,5,1970,1970,0.0,149.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1449,180,21.000000,1470,4,6,1970,1970,0.0,522.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1450,160,21.000000,1484,4,4,1972,1972,0.0,252.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1451,20,80.000000,13384,5,5,1969,1979,194.0,119.0,344.0,...,0,0,0,1,0,0,0,0,1,0
1452,160,21.000000,1533,4,5,1970,1970,0.0,408.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1453,160,21.000000,1526,4,5,1970,1970,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1454,160,21.000000,1936,4,7,1970,1970,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1455,160,21.000000,1894,4,5,1970,1970,0.0,252.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1456,20,160.000000,20000,5,7,1960,1996,0.0,1224.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1457,85,62.000000,10441,5,5,1992,1992,0.0,337.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1458,60,74.000000,9627,7,5,1993,1994,94.0,758.0,0.0,...,0,0,0,1,0,0,0,0,1,0

#### Part 5 The Naive Model

In [21]:
X_train=train
y_train=y #See part 1

In [22]:
X_train

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.000000,8450,7,5,2003,2003,196.0,706.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.000000,9600,6,8,1976,1976,0.0,978.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.000000,11250,7,5,2001,2002,162.0,486.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.000000,9550,7,5,1915,1970,0.0,216.0,0.0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.000000,14260,8,5,2000,2000,350.0,655.0,0.0,...,0,0,0,1,0,0,0,0,1,0
5,50,85.000000,14115,5,5,1993,1995,0.0,732.0,0.0,...,0,0,0,1,0,0,0,0,1,0
6,20,75.000000,10084,8,5,2004,2005,186.0,1369.0,0.0,...,0,0,0,1,0,0,0,0,1,0
7,60,69.305795,10382,7,6,1973,1973,240.0,859.0,32.0,...,0,0,0,1,0,0,0,0,1,0
8,50,51.000000,6120,7,5,1931,1950,0.0,0.0,0.0,...,0,0,0,1,1,0,0,0,0,0
9,190,50.000000,7420,5,6,1939,1950,0.0,851.0,0.0,...,0,0,0,1,0,0,0,0,1,0
10,20,70.000000,11200,5,5,1965,1965,0.0,906.0,0.0,...,0,0,0,1,0,0,0,0,1,0
11,60,85.000000,11924,9,5,2005,2006,286.0,998.0,0.0,...,1,0,0,0,0,0,0,0,0,1
12,20,69.305795,12968,5,6,1962,1962,0.0,737.0,0.0,...,0,0,0,1,0,0,0,0,1,0
13,20,91.000000,10652,7,5,2006,2007,306.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
14,20,69.305795,10920,6,5,1960,1960,212.0,733.0,0.0,...,0,0,0,1,0,0,0,0,1,0
15,45,51.000000,6120,7,8,1929,2001,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
16,20,69.305795,11241,6,7,1970,1970,180.0,578.0,0.0,...,0,0,0,1,0,0,0,0,1,0
17,90,72.000000,10791,4,5,1967,1967,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
18,20,66.000000,13695,5,5,2004,2004,0.0,646.0,0.0,...,0,0,0,1,0,0,0,0,1,0
19,20,70.000000,7560,5,6,1958,1965,0.0,504.0,0.0,...,0,0,0,0,1,0,0,0,0,0
20,60,101.000000,14215,8,5,2005,2006,380.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
21,45,57.000000,7449,7,7,1930,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
22,20,75.000000,9742,8,5,2002,2002,281.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
23,120,44.000000,4224,5,7,1976,1976,0.0,840.0,0.0,...,0,0,0,1,0,0,0,0,1,0
24,20,69.305795,8246,5,8,1968,2001,0.0,188.0,668.0,...,0,0,0,1,0,0,0,0,1,0
25,20,110.000000,14230,8,5,2007,2007,640.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
26,20,60.000000,7200,5,7,1951,2000,0.0,234.0,486.0,...,0,0,0,1,0,0,0,0,1,0
27,20,98.000000,11478,8,5,2007,2008,200.0,1218.0,0.0,...,0,0,0,1,0,0,0,0,1,0
28,20,47.000000,16321,5,6,1957,1997,0.0,1277.0,0.0,...,0,0,0,1,0,0,0,0,1,0
29,30,60.000000,6324,4,6,1927,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,60.000000,21930,5,5,2005,2005,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1431,120,69.305795,4928,6,6,1976,1976,0.0,958.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1432,30,60.000000,10800,4,6,1927,2007,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1433,60,93.000000,10261,6,5,2000,2000,318.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1434,20,80.000000,17400,5,5,1977,1977,0.0,936.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1435,20,80.000000,8400,6,9,1962,2005,237.0,0.0,0.0,...,0,0,0,0,1,0,0,0,0,0
1436,20,60.000000,9000,4,6,1971,1971,0.0,616.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1437,20,96.000000,12444,8,5,2008,2008,426.0,1336.0,0.0,...,1,0,0,0,0,0,0,0,0,1
1438,20,90.000000,7407,6,7,1957,1996,0.0,600.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1439,60,80.000000,11584,7,6,1979,1979,96.0,315.0,110.0,...,0,0,0,1,0,0,0,0,1,0
1440,70,79.000000,11526,6,7,1922,1994,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1441,120,69.305795,4426,6,5,2004,2004,147.0,697.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1442,60,85.000000,11003,10,5,2008,2008,160.0,765.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1443,30,69.305795,8854,6,6,1916,1950,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1444,20,63.000000,8500,7,5,2004,2004,106.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1445,85,70.000000,8400,6,5,1966,1966,0.0,187.0,627.0,...,0,0,0,1,0,0,0,0,1,0
1446,20,69.305795,26142,5,7,1962,1962,189.0,593.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1447,60,80.000000,10000,8,5,1995,1996,438.0,1079.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1448,50,70.000000,11767,4,7,1910,2000,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1449,180,21.000000,1533,5,7,1970,1970,0.0,553.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1450,90,60.000000,9000,5,5,1974,1974,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1451,20,78.000000,9262,8,5,2008,2009,194.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,1
1452,180,35.000000,3675,5,5,2005,2005,80.0,547.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1453,20,90.000000,17217,5,5,2006,2006,0.0,0.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1454,20,62.000000,7500,7,5,2004,2005,0.0,410.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1455,60,62.000000,7917,6,5,1999,2000,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.000000,13175,6,6,1978,1988,119.0,790.0,163.0,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.000000,9042,7,9,1941,2006,0.0,275.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.000000,9717,5,6,1950,1996,0.0,49.0,1029.0,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.000000,9937,5,6,1965,1965,0.0,830.0,290.0,...,0,0,0,1,0,0,0,0,1,0

In [23]:
y_train

0       208500
1       181500
2       223500
3       140000
4       250000
5       143000
6       307000
7       200000
8       129900
9       118000
10      129500
11      345000
12      144000
13      279500
14      157000
15      132000
16      149000
17       90000
18      159000
19      139000
20      325300
21      139400
22      230000
23      129900
24      154000
25      256300
26      134800
27      306000
28      207500
29       68500
         ...
1430    192140
1431    143750
1432     64500
1433    186500
1434    160000
1435    174000
1436    120500
1437    394617
1438    149700
1439    197000
1440    191000
1441    149300
1442    310000
1443    121000
1444    179600
1445    129000
1446    157900
1447    240000
1448    112000
1449     92000
1450    136000
1451    287090
1452    145000
1453     84500
1454    185000
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [24]:
#This null simply predict that the price would be the mean of y_train for all properties
y_test_naivemodel=pd.Series([np.mean(y_train)] * (y_train.size-1))
y_test_naivemodel.head()

0    180921.19589
1    180921.19589
2    180921.19589
3    180921.19589
4    180921.19589
dtype: float64

In [25]:
np.count_nonzero(y_test_naivemodel)

1459

#### Part 6 Evaluate the Performance

In [26]:
#The performance will be evaluated by submitting a file to Kaggle 
#Kaggle uses RMSE for performance evaluation
#The remaining codes in this part: create a Kaggle submission file
sub1=pd.DataFrame(testid)
sub1.head()

     Id
0  1461
1  1462
2  1463
3  1464
4  1465

In [27]:
sub2=pd.DataFrame(y_test_naivemodel,columns=['SalePrice'])
sub2.head()

      SalePrice
0  180921.19589
1  180921.19589
2  180921.19589
3  180921.19589
4  180921.19589

In [29]:
sub=pd.concat([sub1,sub2],axis=1)
sub.head()

     Id     SalePrice
0  1461  180921.19589
1  1462  180921.19589
2  1463  180921.19589
3  1464  180921.19589
4  1465  180921.19589

In [30]:
sub.to_csv('sub_NaiveModel.csv',index=False)

**Kaggle Score 0.42949**

![](NaiveModel.png)